### ISSUE TITLE
[Bug] Infinite loop in entering recovery key

### ISSUE THREAD

**Issue by chlorine3545** [girlbossceo/conduwuit#710]
As the title suggests.

When I entered my recovery key (no matter where), it just disappeared (the input was cleared, I mean) and ... I'm prompted to re-enter it repeatedly. This issue does not occur on a Synapse server.

Additional Info:

- OS: macOS 15
- Browser: Firefox & Chrome
- Client: Element & Cinny (both web)
- Server version: latest

Thanks!

**Comment by girlbossceo** [comment]
What's the actual conduwuit version you're running?

**Comment by chlorine3545** [comment]
> What's the actual conduwuit version you're running?

`docker.io/girlbossceo/conduwuit:main`

https://hub.docker.com/layers/girlbossceo/conduwuit/main/images/sha256-16639c0912f27853403ece829a7cbcdb4ec1d2b18bdb1e091ce3c98132b732c5

**Comment by blakeavato** [comment]
This bug should be caused by #709  This bug caused This bug caused

**Comment by girlbossceo** [comment]
Please check if the latest commit I pushed to main branch fixes your issue

**Comment by Xinayder** [comment]
I have a similar issue, though it happens on Element X on Android. I get the pop-up that my storage keys are out of sync, and upon entering either the recovery key or phrase, the app goes back to the main conversation screen and the popup to update the keys is still there.

Upstream issue is here https://github.com/element-hq/element-x-android/issues/4343

**Comment by girlbossceo** [comment]
Have you checked if main branch of conduwuit fixed it?

**Comment by chlorine3545** [comment]
> Have you checked if main branch of conduwuit fixed it?

Sorry for the delay. The problem seems to be fixed, but in Element web it still shows unvalidated even if the validation was successful (according to other devices).

**Comment by girlbossceo** [comment]
I'm gonna assume this is fixed and the other issue mentioned is a different/unrelated one.
